version: "3"
services:
  api:
    image: mapapylife/api:latest
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=${TZ}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
  cron:
    image: mapapylife/cron:latest
    build: cron
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - TZ=${TZ}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  postgres:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - redis-vol:/data
  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/static:ro
volumes:
  postgres-vol:
  redis-vol:
