version: "3"
services:
  api:
    image: mapapylife/api:latest
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=${TZ}
      - WEB_CONCURRENCY=16
      - FORWARDED_ALLOW_IPS=172.23.0.1, 172.23.0.6
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    networks:
      default:
        ipv4_address: 172.23.0.2
        aliases:
          - api
  cron:
    image: mapapylife/cron:latest
    build: cron
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - TZ=${TZ}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      default:
        ipv4_address: 172.23.0.3
        aliases:
          - cron
  postgres:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.23.0.4
        aliases:
          - postgres
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - redis-vol:/data
    networks:
      default:
        ipv4_address: 172.23.0.5
        aliases:
          - redis
  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/static:ro
    networks:
      default:
        ipv4_address: 172.23.0.6
        aliases:
          - nginx
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
volumes:
  postgres-vol:
  redis-vol:
